<?php
/**
 * ChangeOrderReporting
 *
 * PHP version 5
 *
 * @category Class
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IMN  API
 *
 * # The REST API of IMN system  ## Overview  The REST APIs provide programmatic access to read and write IMN data.   Basically, with this API you will be able to do everything like you were with your browser on https://go.imn.io !    The main features are:  - Register and manage your merchant account  - Declare your source marketplace to get your offers  - Configure your marketplace api credential  - Define the target marketplaces you want to go to, then you will be able to configure:   - the pricing setting    - the shipping settings  - ...and more!      ## Things to keep in mind  ### API Rate Limits  - The IMN REST API is limited to 100 calls/minute.    ### Media type  The default media type for requests and responses is application/json. Where noted, some operations support other content types. If no additional content type is mentioned for a specific operation, then the media type is application/json.    ### Required content type  The required and default encoding for the request and responses is UTF8.    ### Required date time format  All our date time are formatted in ISO 8601 format: 2014-06-24T16:25:00Z.    ### Base URL  The Base URL of the IMN API Order Management REST API conforms to the following template.    https://api.imn.io    All URLs returned by the IMN API are relative to this base URL, and all requests to the REST API must use this base URL template.    You can test our API on https://api-docs.imn.io/swagger-ui\\\\  You can contact us on [gitter, #IMN/API](https://gitter.im/IMN/API)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@imn.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace IMN\Swagger\Client\Model;

use \ArrayAccess;
use \IMN\Swagger\Client\ObjectSerializer;

/**
 * ChangeOrderReporting Class Doc Comment
 *
 * @category Class
 * @description The reporting related to a change order operation
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChangeOrderReporting implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'changeOrderReporting';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'correlation_id' => '\IMN\Swagger\Client\Model\CorrelationId',
        'change_type' => '\IMN\Swagger\Client\Model\OrderChangeType',
        'source_type' => '\IMN\Swagger\Client\Model\OperationSourceType',
        'source_user_id' => '\IMN\Swagger\Client\Model\UserId',
        'source_user_name' => 'string',
        'creation_utc_date' => '\DateTime',
        'processing_status' => '\IMN\Swagger\Client\Model\ProcessingStatus',
        'last_update_utc_date' => '\DateTime',
        'error_message' => 'string',
        'ip_address' => 'string',
        'test_mode' => 'bool',
        'details' => 'map[string,object]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'correlation_id' => null,
        'change_type' => null,
        'source_type' => null,
        'source_user_id' => null,
        'source_user_name' => null,
        'creation_utc_date' => 'date-time',
        'processing_status' => null,
        'last_update_utc_date' => 'date-time',
        'error_message' => null,
        'ip_address' => null,
        'test_mode' => null,
        'details' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'correlation_id' => 'correlationId',
        'change_type' => 'changeType',
        'source_type' => 'sourceType',
        'source_user_id' => 'sourceUserId',
        'source_user_name' => 'sourceUserName',
        'creation_utc_date' => 'creationUtcDate',
        'processing_status' => 'processingStatus',
        'last_update_utc_date' => 'lastUpdateUtcDate',
        'error_message' => 'errorMessage',
        'ip_address' => 'ipAddress',
        'test_mode' => 'testMode',
        'details' => 'details'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'correlation_id' => 'setCorrelationId',
        'change_type' => 'setChangeType',
        'source_type' => 'setSourceType',
        'source_user_id' => 'setSourceUserId',
        'source_user_name' => 'setSourceUserName',
        'creation_utc_date' => 'setCreationUtcDate',
        'processing_status' => 'setProcessingStatus',
        'last_update_utc_date' => 'setLastUpdateUtcDate',
        'error_message' => 'setErrorMessage',
        'ip_address' => 'setIpAddress',
        'test_mode' => 'setTestMode',
        'details' => 'setDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'correlation_id' => 'getCorrelationId',
        'change_type' => 'getChangeType',
        'source_type' => 'getSourceType',
        'source_user_id' => 'getSourceUserId',
        'source_user_name' => 'getSourceUserName',
        'creation_utc_date' => 'getCreationUtcDate',
        'processing_status' => 'getProcessingStatus',
        'last_update_utc_date' => 'getLastUpdateUtcDate',
        'error_message' => 'getErrorMessage',
        'ip_address' => 'getIpAddress',
        'test_mode' => 'getTestMode',
        'details' => 'getDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['correlation_id'] = isset($data['correlation_id']) ? $data['correlation_id'] : null;
        $this->container['change_type'] = isset($data['change_type']) ? $data['change_type'] : null;
        $this->container['source_type'] = isset($data['source_type']) ? $data['source_type'] : null;
        $this->container['source_user_id'] = isset($data['source_user_id']) ? $data['source_user_id'] : null;
        $this->container['source_user_name'] = isset($data['source_user_name']) ? $data['source_user_name'] : null;
        $this->container['creation_utc_date'] = isset($data['creation_utc_date']) ? $data['creation_utc_date'] : null;
        $this->container['processing_status'] = isset($data['processing_status']) ? $data['processing_status'] : null;
        $this->container['last_update_utc_date'] = isset($data['last_update_utc_date']) ? $data['last_update_utc_date'] : null;
        $this->container['error_message'] = isset($data['error_message']) ? $data['error_message'] : null;
        $this->container['ip_address'] = isset($data['ip_address']) ? $data['ip_address'] : null;
        $this->container['test_mode'] = isset($data['test_mode']) ? $data['test_mode'] : null;
        $this->container['details'] = isset($data['details']) ? $data['details'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['correlation_id'] === null) {
            $invalidProperties[] = "'correlation_id' can't be null";
        }
        if ($this->container['change_type'] === null) {
            $invalidProperties[] = "'change_type' can't be null";
        }
        if ($this->container['source_type'] === null) {
            $invalidProperties[] = "'source_type' can't be null";
        }
        if ($this->container['source_user_id'] === null) {
            $invalidProperties[] = "'source_user_id' can't be null";
        }
        if ($this->container['source_user_name'] === null) {
            $invalidProperties[] = "'source_user_name' can't be null";
        }
        if ($this->container['creation_utc_date'] === null) {
            $invalidProperties[] = "'creation_utc_date' can't be null";
        }
        if ($this->container['processing_status'] === null) {
            $invalidProperties[] = "'processing_status' can't be null";
        }
        if ($this->container['last_update_utc_date'] === null) {
            $invalidProperties[] = "'last_update_utc_date' can't be null";
        }
        if ($this->container['ip_address'] === null) {
            $invalidProperties[] = "'ip_address' can't be null";
        }
        if ($this->container['test_mode'] === null) {
            $invalidProperties[] = "'test_mode' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['correlation_id'] === null) {
            return false;
        }
        if ($this->container['change_type'] === null) {
            return false;
        }
        if ($this->container['source_type'] === null) {
            return false;
        }
        if ($this->container['source_user_id'] === null) {
            return false;
        }
        if ($this->container['source_user_name'] === null) {
            return false;
        }
        if ($this->container['creation_utc_date'] === null) {
            return false;
        }
        if ($this->container['processing_status'] === null) {
            return false;
        }
        if ($this->container['last_update_utc_date'] === null) {
            return false;
        }
        if ($this->container['ip_address'] === null) {
            return false;
        }
        if ($this->container['test_mode'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets correlation_id
     *
     * @return \IMN\Swagger\Client\Model\CorrelationId
     */
    public function getCorrelationId()
    {
        return $this->container['correlation_id'];
    }

    /**
     * Sets correlation_id
     *
     * @param \IMN\Swagger\Client\Model\CorrelationId $correlation_id correlation_id
     *
     * @return $this
     */
    public function setCorrelationId($correlation_id)
    {
        $this->container['correlation_id'] = $correlation_id;

        return $this;
    }

    /**
     * Gets change_type
     *
     * @return \IMN\Swagger\Client\Model\OrderChangeType
     */
    public function getChangeType()
    {
        return $this->container['change_type'];
    }

    /**
     * Sets change_type
     *
     * @param \IMN\Swagger\Client\Model\OrderChangeType $change_type change_type
     *
     * @return $this
     */
    public function setChangeType($change_type)
    {
        $this->container['change_type'] = $change_type;

        return $this;
    }

    /**
     * Gets source_type
     *
     * @return \IMN\Swagger\Client\Model\OperationSourceType
     */
    public function getSourceType()
    {
        return $this->container['source_type'];
    }

    /**
     * Sets source_type
     *
     * @param \IMN\Swagger\Client\Model\OperationSourceType $source_type source_type
     *
     * @return $this
     */
    public function setSourceType($source_type)
    {
        $this->container['source_type'] = $source_type;

        return $this;
    }

    /**
     * Gets source_user_id
     *
     * @return \IMN\Swagger\Client\Model\UserId
     */
    public function getSourceUserId()
    {
        return $this->container['source_user_id'];
    }

    /**
     * Sets source_user_id
     *
     * @param \IMN\Swagger\Client\Model\UserId $source_user_id source_user_id
     *
     * @return $this
     */
    public function setSourceUserId($source_user_id)
    {
        $this->container['source_user_id'] = $source_user_id;

        return $this;
    }

    /**
     * Gets source_user_name
     *
     * @return string
     */
    public function getSourceUserName()
    {
        return $this->container['source_user_name'];
    }

    /**
     * Sets source_user_name
     *
     * @param string $source_user_name source_user_name
     *
     * @return $this
     */
    public function setSourceUserName($source_user_name)
    {
        $this->container['source_user_name'] = $source_user_name;

        return $this;
    }

    /**
     * Gets creation_utc_date
     *
     * @return \DateTime
     */
    public function getCreationUtcDate()
    {
        return $this->container['creation_utc_date'];
    }

    /**
     * Sets creation_utc_date
     *
     * @param \DateTime $creation_utc_date The creation UTC date of the execution
     *
     * @return $this
     */
    public function setCreationUtcDate($creation_utc_date)
    {
        $this->container['creation_utc_date'] = $creation_utc_date;

        return $this;
    }

    /**
     * Gets processing_status
     *
     * @return \IMN\Swagger\Client\Model\ProcessingStatus
     */
    public function getProcessingStatus()
    {
        return $this->container['processing_status'];
    }

    /**
     * Sets processing_status
     *
     * @param \IMN\Swagger\Client\Model\ProcessingStatus $processing_status processing_status
     *
     * @return $this
     */
    public function setProcessingStatus($processing_status)
    {
        $this->container['processing_status'] = $processing_status;

        return $this;
    }

    /**
     * Gets last_update_utc_date
     *
     * @return \DateTime
     */
    public function getLastUpdateUtcDate()
    {
        return $this->container['last_update_utc_date'];
    }

    /**
     * Sets last_update_utc_date
     *
     * @param \DateTime $last_update_utc_date The last update UTC date of the execution
     *
     * @return $this
     */
    public function setLastUpdateUtcDate($last_update_utc_date)
    {
        $this->container['last_update_utc_date'] = $last_update_utc_date;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string $error_message The error message during the execution
     *
     * @return $this
     */
    public function setErrorMessage($error_message)
    {
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets ip_address
     *
     * @return string
     */
    public function getIpAddress()
    {
        return $this->container['ip_address'];
    }

    /**
     * Sets ip_address
     *
     * @param string $ip_address The IP address who request this operation
     *
     * @return $this
     */
    public function setIpAddress($ip_address)
    {
        $this->container['ip_address'] = $ip_address;

        return $this;
    }

    /**
     * Gets test_mode
     *
     * @return bool
     */
    public function getTestMode()
    {
        return $this->container['test_mode'];
    }

    /**
     * Sets test_mode
     *
     * @param bool $test_mode This operation was a test
     *
     * @return $this
     */
    public function setTestMode($test_mode)
    {
        $this->container['test_mode'] = $test_mode;

        return $this;
    }

    /**
     * Gets details
     *
     * @return map[string,object]
     */
    public function getDetails()
    {
        return $this->container['details'];
    }

    /**
     * Sets details
     *
     * @param map[string,object] $details details
     *
     * @return $this
     */
    public function setDetails($details)
    {
        $this->container['details'] = $details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


