<?php
/**
 * OrderItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IMN  API
 *
 * # The REST API of IMN system  ## Overview  The REST APIs provide programmatic access to read and write IMN data.   Basically, with this API you will be able to do everything like you were with your browser on https://go.imn.io !    The main features are:  - Register and manage your merchant account  - Declare your source marketplace to get your offers  - Configure your marketplace api credential  - Define the target marketplaces you want to go to, then you will be able to configure:   - the pricing setting    - the shipping settings  - ...and more!      ## Things to keep in mind  ### API Rate Limits  - The IMN REST API is limited to 100 calls/minute.    ### Media type  The default media type for requests and responses is application/json. Where noted, some operations support other content types. If no additional content type is mentioned for a specific operation, then the media type is application/json.    ### Required content type  The required and default encoding for the request and responses is UTF8.    ### Required date time format  All our date time are formatted in ISO 8601 format: 2014-06-24T16:25:00Z.    ### Base URL  The Base URL of the IMN API Order Management REST API conforms to the following template.    https://api.imn.io    All URLs returned by the IMN API are relative to this base URL, and all requests to the REST API must use this base URL template.    You can test our API on https://api-docs.imn.io/swagger-ui\\\\  You can contact us on [gitter, #IMN/API](https://gitter.im/IMN/API)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@imn.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace IMN\Swagger\Client\Model;

use \ArrayAccess;
use \IMN\Swagger\Client\ObjectSerializer;

/**
 * OrderItem Class Doc Comment
 *
 * @category Class
 * @description Describe an order item.
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'orderItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'title' => 'string',
        'condition' => 'string',
        'image_url' => '\IMN\Swagger\Client\Model\HttpUrl',
        'merchant_offer_sku' => '\IMN\Swagger\Client\Model\Sku',
        'gtin' => '\IMN\Swagger\Client\Model\Gtin',
        'marketplace_product_id' => 'string',
        'marketplace_product_url' => '\IMN\Swagger\Client\Model\HttpUrl',
        'item_price' => 'float',
        'item_tax' => 'float',
        'quantity' => 'float',
        'shipping_price' => 'float',
        'total_price' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'title' => null,
        'condition' => null,
        'image_url' => null,
        'merchant_offer_sku' => null,
        'gtin' => null,
        'marketplace_product_id' => null,
        'marketplace_product_url' => null,
        'item_price' => 'decimal',
        'item_tax' => 'decimal',
        'quantity' => 'decimal',
        'shipping_price' => 'decimal',
        'total_price' => 'decimal'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'title' => 'title',
        'condition' => 'condition',
        'image_url' => 'imageUrl',
        'merchant_offer_sku' => 'merchantOfferSku',
        'gtin' => 'gtin',
        'marketplace_product_id' => 'marketplaceProductId',
        'marketplace_product_url' => 'marketplaceProductUrl',
        'item_price' => 'itemPrice',
        'item_tax' => 'itemTax',
        'quantity' => 'quantity',
        'shipping_price' => 'shippingPrice',
        'total_price' => 'totalPrice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'title' => 'setTitle',
        'condition' => 'setCondition',
        'image_url' => 'setImageUrl',
        'merchant_offer_sku' => 'setMerchantOfferSku',
        'gtin' => 'setGtin',
        'marketplace_product_id' => 'setMarketplaceProductId',
        'marketplace_product_url' => 'setMarketplaceProductUrl',
        'item_price' => 'setItemPrice',
        'item_tax' => 'setItemTax',
        'quantity' => 'setQuantity',
        'shipping_price' => 'setShippingPrice',
        'total_price' => 'setTotalPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'title' => 'getTitle',
        'condition' => 'getCondition',
        'image_url' => 'getImageUrl',
        'merchant_offer_sku' => 'getMerchantOfferSku',
        'gtin' => 'getGtin',
        'marketplace_product_id' => 'getMarketplaceProductId',
        'marketplace_product_url' => 'getMarketplaceProductUrl',
        'item_price' => 'getItemPrice',
        'item_tax' => 'getItemTax',
        'quantity' => 'getQuantity',
        'shipping_price' => 'getShippingPrice',
        'total_price' => 'getTotalPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['condition'] = isset($data['condition']) ? $data['condition'] : null;
        $this->container['image_url'] = isset($data['image_url']) ? $data['image_url'] : null;
        $this->container['merchant_offer_sku'] = isset($data['merchant_offer_sku']) ? $data['merchant_offer_sku'] : null;
        $this->container['gtin'] = isset($data['gtin']) ? $data['gtin'] : null;
        $this->container['marketplace_product_id'] = isset($data['marketplace_product_id']) ? $data['marketplace_product_id'] : null;
        $this->container['marketplace_product_url'] = isset($data['marketplace_product_url']) ? $data['marketplace_product_url'] : null;
        $this->container['item_price'] = isset($data['item_price']) ? $data['item_price'] : null;
        $this->container['item_tax'] = isset($data['item_tax']) ? $data['item_tax'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['shipping_price'] = isset($data['shipping_price']) ? $data['shipping_price'] : null;
        $this->container['total_price'] = isset($data['total_price']) ? $data['total_price'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title The title of the order item
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets condition
     *
     * @return string
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     *
     * @param string $condition The condition of the order item
     *
     * @return $this
     */
    public function setCondition($condition)
    {
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return \IMN\Swagger\Client\Model\HttpUrl
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param \IMN\Swagger\Client\Model\HttpUrl $image_url image_url
     *
     * @return $this
     */
    public function setImageUrl($image_url)
    {
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets merchant_offer_sku
     *
     * @return \IMN\Swagger\Client\Model\Sku
     */
    public function getMerchantOfferSku()
    {
        return $this->container['merchant_offer_sku'];
    }

    /**
     * Sets merchant_offer_sku
     *
     * @param \IMN\Swagger\Client\Model\Sku $merchant_offer_sku merchant_offer_sku
     *
     * @return $this
     */
    public function setMerchantOfferSku($merchant_offer_sku)
    {
        $this->container['merchant_offer_sku'] = $merchant_offer_sku;

        return $this;
    }

    /**
     * Gets gtin
     *
     * @return \IMN\Swagger\Client\Model\Gtin
     */
    public function getGtin()
    {
        return $this->container['gtin'];
    }

    /**
     * Sets gtin
     *
     * @param \IMN\Swagger\Client\Model\Gtin $gtin gtin
     *
     * @return $this
     */
    public function setGtin($gtin)
    {
        $this->container['gtin'] = $gtin;

        return $this;
    }

    /**
     * Gets marketplace_product_id
     *
     * @return string
     */
    public function getMarketplaceProductId()
    {
        return $this->container['marketplace_product_id'];
    }

    /**
     * Sets marketplace_product_id
     *
     * @param string $marketplace_product_id The marketplace product identifier of the order item
     *
     * @return $this
     */
    public function setMarketplaceProductId($marketplace_product_id)
    {
        $this->container['marketplace_product_id'] = $marketplace_product_id;

        return $this;
    }

    /**
     * Gets marketplace_product_url
     *
     * @return \IMN\Swagger\Client\Model\HttpUrl
     */
    public function getMarketplaceProductUrl()
    {
        return $this->container['marketplace_product_url'];
    }

    /**
     * Sets marketplace_product_url
     *
     * @param \IMN\Swagger\Client\Model\HttpUrl $marketplace_product_url marketplace_product_url
     *
     * @return $this
     */
    public function setMarketplaceProductUrl($marketplace_product_url)
    {
        $this->container['marketplace_product_url'] = $marketplace_product_url;

        return $this;
    }

    /**
     * Gets item_price
     *
     * @return float
     */
    public function getItemPrice()
    {
        return $this->container['item_price'];
    }

    /**
     * Sets item_price
     *
     * @param float $item_price The price of the order item
     *
     * @return $this
     */
    public function setItemPrice($item_price)
    {
        $this->container['item_price'] = $item_price;

        return $this;
    }

    /**
     * Gets item_tax
     *
     * @return float
     */
    public function getItemTax()
    {
        return $this->container['item_tax'];
    }

    /**
     * Sets item_tax
     *
     * @param float $item_tax The tax of the order item
     *
     * @return $this
     */
    public function setItemTax($item_tax)
    {
        $this->container['item_tax'] = $item_tax;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float $quantity The quantity of the order item
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets shipping_price
     *
     * @return float
     */
    public function getShippingPrice()
    {
        return $this->container['shipping_price'];
    }

    /**
     * Sets shipping_price
     *
     * @param float $shipping_price The shipping price of the order item
     *
     * @return $this
     */
    public function setShippingPrice($shipping_price)
    {
        $this->container['shipping_price'] = $shipping_price;

        return $this;
    }

    /**
     * Gets total_price
     *
     * @return float
     */
    public function getTotalPrice()
    {
        return $this->container['total_price'];
    }

    /**
     * Sets total_price
     *
     * @param float $total_price The total price of the order item
     *
     * @return $this
     */
    public function setTotalPrice($total_price)
    {
        $this->container['total_price'] = $total_price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


