<?php
/**
 * OrderReceived
 *
 * PHP version 5
 *
 * @category Class
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IMN  API
 *
 * # The REST API of IMN system  ## Overview  The REST APIs provide programmatic access to read and write IMN data.   Basically, with this API you will be able to do everything like you were with your browser on https://go.imn.io !    The main features are:  - Register and manage your merchant account  - Declare your source marketplace to get your offers  - Configure your marketplace api credential  - Define the target marketplaces you want to go to, then you will be able to configure:   - the pricing setting    - the shipping settings  - ...and more!      ## Things to keep in mind  ### API Rate Limits  - The IMN REST API is limited to 100 calls/minute.    ### Media type  The default media type for requests and responses is application/json. Where noted, some operations support other content types. If no additional content type is mentioned for a specific operation, then the media type is application/json.    ### Required content type  The required and default encoding for the request and responses is UTF8.    ### Required date time format  All our date time are formatted in ISO 8601 format: 2014-06-24T16:25:00Z.    ### Base URL  The Base URL of the IMN API Order Management REST API conforms to the following template.    https://api.imn.io    All URLs returned by the IMN API are relative to this base URL, and all requests to the REST API must use this base URL template.    You can test our API on https://api-docs.imn.io/swagger-ui\\\\  You can contact us on [gitter, #IMN/API](https://gitter.im/IMN/API)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@imn.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace IMN\Swagger\Client\Model;

use \ArrayAccess;
use \IMN\Swagger\Client\ObjectSerializer;

/**
 * OrderReceived Class Doc Comment
 *
 * @category Class
 * @description This event his a technical one. It is stored in the event hub before it&#39;s processed by the OrderActor. The order actor will create business event like order created or updated. OrderReceived will be not be stored in the Event Store.
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderReceived implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'orderReceived';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'identifier' => '\IMN\Swagger\Client\Model\OrderIdentifier',
        'general_info' => '\IMN\Swagger\Client\Model\OrderGeneralInfo',
        'pricing_info' => '\IMN\Swagger\Client\Model\OrderPricingInfo',
        'billing_info' => '\IMN\Swagger\Client\Model\OrderBillingInfo',
        'shipping_info' => '\IMN\Swagger\Client\Model\OrderShippingInfo',
        'order_items' => '\IMN\Swagger\Client\Model\OrderItems'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'identifier' => null,
        'general_info' => null,
        'pricing_info' => null,
        'billing_info' => null,
        'shipping_info' => null,
        'order_items' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identifier' => 'identifier',
        'general_info' => 'generalInfo',
        'pricing_info' => 'pricingInfo',
        'billing_info' => 'billingInfo',
        'shipping_info' => 'shippingInfo',
        'order_items' => 'orderItems'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identifier' => 'setIdentifier',
        'general_info' => 'setGeneralInfo',
        'pricing_info' => 'setPricingInfo',
        'billing_info' => 'setBillingInfo',
        'shipping_info' => 'setShippingInfo',
        'order_items' => 'setOrderItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identifier' => 'getIdentifier',
        'general_info' => 'getGeneralInfo',
        'pricing_info' => 'getPricingInfo',
        'billing_info' => 'getBillingInfo',
        'shipping_info' => 'getShippingInfo',
        'order_items' => 'getOrderItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['identifier'] = isset($data['identifier']) ? $data['identifier'] : null;
        $this->container['general_info'] = isset($data['general_info']) ? $data['general_info'] : null;
        $this->container['pricing_info'] = isset($data['pricing_info']) ? $data['pricing_info'] : null;
        $this->container['billing_info'] = isset($data['billing_info']) ? $data['billing_info'] : null;
        $this->container['shipping_info'] = isset($data['shipping_info']) ? $data['shipping_info'] : null;
        $this->container['order_items'] = isset($data['order_items']) ? $data['order_items'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['identifier'] === null) {
            $invalidProperties[] = "'identifier' can't be null";
        }
        if ($this->container['general_info'] === null) {
            $invalidProperties[] = "'general_info' can't be null";
        }
        if ($this->container['pricing_info'] === null) {
            $invalidProperties[] = "'pricing_info' can't be null";
        }
        if ($this->container['billing_info'] === null) {
            $invalidProperties[] = "'billing_info' can't be null";
        }
        if ($this->container['shipping_info'] === null) {
            $invalidProperties[] = "'shipping_info' can't be null";
        }
        if ($this->container['order_items'] === null) {
            $invalidProperties[] = "'order_items' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['identifier'] === null) {
            return false;
        }
        if ($this->container['general_info'] === null) {
            return false;
        }
        if ($this->container['pricing_info'] === null) {
            return false;
        }
        if ($this->container['billing_info'] === null) {
            return false;
        }
        if ($this->container['shipping_info'] === null) {
            return false;
        }
        if ($this->container['order_items'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets identifier
     *
     * @return \IMN\Swagger\Client\Model\OrderIdentifier
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param \IMN\Swagger\Client\Model\OrderIdentifier $identifier identifier
     *
     * @return $this
     */
    public function setIdentifier($identifier)
    {
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets general_info
     *
     * @return \IMN\Swagger\Client\Model\OrderGeneralInfo
     */
    public function getGeneralInfo()
    {
        return $this->container['general_info'];
    }

    /**
     * Sets general_info
     *
     * @param \IMN\Swagger\Client\Model\OrderGeneralInfo $general_info general_info
     *
     * @return $this
     */
    public function setGeneralInfo($general_info)
    {
        $this->container['general_info'] = $general_info;

        return $this;
    }

    /**
     * Gets pricing_info
     *
     * @return \IMN\Swagger\Client\Model\OrderPricingInfo
     */
    public function getPricingInfo()
    {
        return $this->container['pricing_info'];
    }

    /**
     * Sets pricing_info
     *
     * @param \IMN\Swagger\Client\Model\OrderPricingInfo $pricing_info pricing_info
     *
     * @return $this
     */
    public function setPricingInfo($pricing_info)
    {
        $this->container['pricing_info'] = $pricing_info;

        return $this;
    }

    /**
     * Gets billing_info
     *
     * @return \IMN\Swagger\Client\Model\OrderBillingInfo
     */
    public function getBillingInfo()
    {
        return $this->container['billing_info'];
    }

    /**
     * Sets billing_info
     *
     * @param \IMN\Swagger\Client\Model\OrderBillingInfo $billing_info billing_info
     *
     * @return $this
     */
    public function setBillingInfo($billing_info)
    {
        $this->container['billing_info'] = $billing_info;

        return $this;
    }

    /**
     * Gets shipping_info
     *
     * @return \IMN\Swagger\Client\Model\OrderShippingInfo
     */
    public function getShippingInfo()
    {
        return $this->container['shipping_info'];
    }

    /**
     * Sets shipping_info
     *
     * @param \IMN\Swagger\Client\Model\OrderShippingInfo $shipping_info shipping_info
     *
     * @return $this
     */
    public function setShippingInfo($shipping_info)
    {
        $this->container['shipping_info'] = $shipping_info;

        return $this;
    }

    /**
     * Gets order_items
     *
     * @return \IMN\Swagger\Client\Model\OrderItems
     */
    public function getOrderItems()
    {
        return $this->container['order_items'];
    }

    /**
     * Sets order_items
     *
     * @param \IMN\Swagger\Client\Model\OrderItems $order_items order_items
     *
     * @return $this
     */
    public function setOrderItems($order_items)
    {
        $this->container['order_items'] = $order_items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


