<?php
/**
 * RefundReason
 *
 * PHP version 5
 *
 * @category Class
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IMN  API
 *
 * # The REST API of IMN system  ## Overview  The REST APIs provide programmatic access to read and write IMN data.   Basically, with this API you will be able to do everything like you were with your browser on https://go.imn.io !    The main features are:  - Register and manage your merchant account  - Declare your source marketplace to get your offers  - Configure your marketplace api credential  - Define the target marketplaces you want to go to, then you will be able to configure:   - the pricing setting    - the shipping settings  - ...and more!      ## Things to keep in mind  ### API Rate Limits  - The IMN REST API is limited to 100 calls/minute.    ### Media type  The default media type for requests and responses is application/json. Where noted, some operations support other content types. If no additional content type is mentioned for a specific operation, then the media type is application/json.    ### Required content type  The required and default encoding for the request and responses is UTF8.    ### Required date time format  All our date time are formatted in ISO 8601 format: 2014-06-24T16:25:00Z.    ### Base URL  The Base URL of the IMN API Order Management REST API conforms to the following template.    https://api.imn.io    All URLs returned by the IMN API are relative to this base URL, and all requests to the REST API must use this base URL template.    You can test our API on https://api-docs.imn.io/swagger-ui\\\\  You can contact us on [gitter, #IMN/API](https://gitter.im/IMN/API)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@imn.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace IMN\Swagger\Client\Model;
use \IMN\Swagger\Client\ObjectSerializer;

/**
 * RefundReason Class Doc Comment
 *
 * @category Class
 * @description The reason why you refund the order
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RefundReason
{
    /**
     * Possible values of this enum
     */
    const BUYER_WARRANTY_OR_RETRACTATION = 'BuyerWarrantyOrRetractation';
    const WRONG_PRICE = 'WrongPrice';
    const LATE_DELIVERY = 'LateDelivery';
    const INCORRECT_DELIVERY = 'IncorrectDelivery';
    const INCOMPLETE_DELIVERY = 'IncompleteDelivery';
    const DAMAGED_DELIVERY = 'DamagedDelivery';
    const BUYER_FEEDBACK_TIMEOUT = 'BuyerFeedbackTimeout';
    const BUYER_AGREEMENT = 'BuyerAgreement';
    const BUYER_CANCELLED = 'BuyerCancelled';
    const NO_INVENTORY = 'NoInventory';
    const SHIPPING_ADDRESS_UNDELIVERABLE = 'ShippingAddressUndeliverable';
    const OTHER = 'Other';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BUYER_WARRANTY_OR_RETRACTATION,
            self::WRONG_PRICE,
            self::LATE_DELIVERY,
            self::INCORRECT_DELIVERY,
            self::INCOMPLETE_DELIVERY,
            self::DAMAGED_DELIVERY,
            self::BUYER_FEEDBACK_TIMEOUT,
            self::BUYER_AGREEMENT,
            self::BUYER_CANCELLED,
            self::NO_INVENTORY,
            self::SHIPPING_ADDRESS_UNDELIVERABLE,
            self::OTHER,
        ];
    }
}


