<?php
/**
 * CarrierCodeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  IMN\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IMN  API
 *
 * # The REST API of IMN system  ## Overview  The REST APIs provide programmatic access to read and write IMN data.   Basically, with this API you will be able to do everything like you were with your browser on https://go.imn.io !    The main features are:  - Register and manage your merchant account  - Declare your source marketplace to get your offers  - Configure your marketplace api credential  - Define the target marketplaces you want to go to, then you will be able to configure:   - the pricing setting    - the shipping settings  - ...and more!      ## Things to keep in mind  ### API Rate Limits  - The IMN REST API is limited to 100 calls/minute.    ### Media type  The default media type for requests and responses is application/json. Where noted, some operations support other content types. If no additional content type is mentioned for a specific operation, then the media type is application/json.    ### Required content type  The required and default encoding for the request and responses is UTF8.    ### Required date time format  All our date time are formatted in ISO 8601 format: 2014-06-24T16:25:00Z.    ### Base URL  The Base URL of the IMN API Order Management REST API conforms to the following template.    https://api.imn.io    All URLs returned by the IMN API are relative to this base URL, and all requests to the REST API must use this base URL template.    You can test our API on https://api-docs.imn.io/swagger-ui\\\\  You can contact us on [gitter, #IMN/API](https://gitter.im/IMN/API)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@imn.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace IMN\Swagger\Client;

/**
 * CarrierCodeTest Class Doc Comment
 *
 * @category    Class */
// * @description The carrier code related to the shipping * DeutschePost: DeutschePost * DHL: DHL * GLS: GLS * TNT: TNT * UPS: UPS * DPD: DPD * FEDEX: FEDEX * 4PX: 4PX * Bpost: Bpost * ChinaEMSePacket: China EMS (ePacket) * ChinaPost: China Post * Chronopost: Chronopost * CNEExpress: CNE Express * ColisPrive: Colis PrivÃ© * Colissimo: Colissimo * GEODIS: GEODIS * LaPosteCourrier: La Poste - Courrier * MalaysiaPost: Malaysia Post * MondialRelay: Mondial Relay * PostNL: PostNL * RelaisColis: Relais Colis * RoyalMail: Royal Mail * SFExpress: SF Express * SFCService: SFC Service * SingaporePost: Singapore Post * USPS: USPS * Yanwen: Yanwen * AMATI: AMATI * BRTID: BRTID * BRTRIFMIT: BRTRIFMIT * BRTSPED: BRTSPED * CORREOS: CORREOS * ENERGO: ENERGO * FERCAM: FERCAM * NEXIVE: NEXIVE * ItalianPost: Italian Post * SDA: SDA * SGTFlyer: SGT Flyer * TECNOTRANS: TECNOTRANS * Bursped: Bursped * Cargoline: Cargoline * Computeruniverse: Computeruniverse * Dachser: Dachser * DHLFreight: DHL Freight * dtl: dtl * Emons: Emons * GEL: GEL * Hellmann: Hellmann * Hermes: Hermes * Hermes2MH: Hermes 2 MH * IDSLogistik: IDS Logistik * Iloxx: Iloxx * KuehneNagel: Kuehne &amp; Nagel * Marktanlieferung: Marktanlieferung * Rhenus: Rhenus * Schenker: Schenker * SpeditionGuettler: Spedition Guettler
/**
 * @package     IMN\Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CarrierCodeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CarrierCode"
     */
    public function testCarrierCode()
    {
    }
}
